name: CICD Pipeline

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'temurin'
            architecture: x64
            cache: maven
      - name: Verify with maven
        run: mvn --batch-mode --update-snapshots verify

  push:
    name: Push Docker image to Docker hub
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    needs: build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: darwin5/studspace-backend
      - name: Build and push image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          